#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Ensure the script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

# Update package list and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Clear existing config file and write the new configuration
cat <<EOF | tee /etc/haproxy/haproxy.cfg
frontend habib-frontend
    bind *:80
    mode http
    default_backend habib-backend

backend habib-backend
    balance roundrobin
    server 6104-web-01 34.227.8.126:80 check
    server 6238-web-02 3.87.237.241:80 check
EOF

# Enable HAProxy to be started by init script
echo "ENABLED=1" | tee /etc/default/haproxy

# Restart HAProxy to apply the configuration
service haproxy restart

# Verify the HAProxy configuration
echo "HAProxy configuration complete. Verifying..."
curl -sI http://localhost | grep X-Served-By